Repository input-output-hk/catalyst-toolbox, pull requests merged in 2021-05, with the labels that each got.

#6 Pushwoosh notifications
  Cargo.lock
  README.md
  catalyst-toolbox-cli/Cargo.toml
  catalyst-toolbox-cli/src/cli/mod.rs
  catalyst-toolbox-cli/src/cli/notifications/api_params.rs
  catalyst-toolbox-cli/src/cli/notifications/mod.rs
  catalyst-toolbox-cli/src/cli/notifications/requests/create_message.rs
  catalyst-toolbox-cli/src/cli/notifications/requests/mod.rs
  catalyst-toolbox-cli/src/cli/notifications/responses/create_message.rs
  catalyst-toolbox-cli/src/cli/notifications/responses/mod.rs
  catalyst-toolbox-cli/src/cli/notifications/send.rs
Labels: enhancement

#7 Rust gh actions
  .github/workflows/audit.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  ci/release-info.py
  ci/strip-own-version-from-cargo-lock.pl
Labels: CI

#4 Fixed precision error
  catalyst-toolbox-cli/src/cli/rewards/voters.rs
Labels: bug

#12 Refactor into single crate with lib and bin parts
  Cargo.lock
  Cargo.toml
  README.md
  build.rs
  catalyst-toolbox-cli/Cargo.toml
  catalyst-toolbox-lib/Cargo.toml
  catalyst-toolbox-lib/src/lib.rs
  ci/release-info.py
  src/bin/catalyst-toolbox.rs
  src/bin/cli/mod.rs
  src/bin/cli/notifications/api_params.rs
  src/bin/cli/notifications/mod.rs
  src/bin/cli/notifications/send.rs
  src/bin/cli/recovery/mod.rs
  src/bin/cli/recovery/tally.rs
  src/bin/cli/recovery/votes.rs
  src/bin/cli/rewards/mod.rs
  src/bin/cli/rewards/voters.rs
  src/lib.rs
  src/notifications/mod.rs
  src/notifications/requests/create_message.rs
  src/notifications/requests/mod.rs
  src/notifications/responses/create_message.rs
  src/notifications/responses/mod.rs
  src/notifications/send.rs
  src/recovery/mod.rs
  src/recovery/tally.rs
  src/rewards/mod.rs
  src/rewards/voters.rs
  testing/catalyst-toolbox-tests/Cargo.toml
  testing/catalyst-toolbox-tests/src/lib.rs
  tests/block0.bin
  tests/logs/2021-05-06_14.log
  tests/tally/blockchain.rs
  tests/tally/generator.rs
  tests/tally/main.rs
Labels: refactor

#11 Add tests for votes outside voting phase
  tests/tally/main.rs
Labels: testing
