Repository input-output-hk/catalyst-toolbox, pull requests merged in 2021-08, with the labels that each got.

#38 Fix clippy errors for rust 1.54
  src/bin/cli/ideascale/mod.rs
  src/bin/cli/logs/compare.rs
  src/bin/cli/logs/sentry/mod.rs
  src/bin/cli/recovery/tally.rs
  src/ideascale/mod.rs
  src/recovery/tally.rs
Labels: refactor

#43 Update documentation and tests of push subcommand
  README.md
  tests/notifications/main.rs
Labels: documentation

#44 Document QR code protocol and qr-code command
  README.md
  doc/private-key-and-qr-code.md
Labels: documentation

#45 Fix use of secrets in the test workflow
  .github/workflows/test.yml
Labels: CI

#48 Move secrets to job level
  .github/workflows/test.yml
Labels: CI

#47 Allow only one vote per account/proposal
  Cargo.lock
  Cargo.toml
  src/recovery/tally.rs
  tests/tally/generator.rs
  tests/tally/main.rs
Labels: enhancement

#50 Archival tool
  Cargo.lock
  Cargo.toml
  README.md
  src/archive.rs
  src/bin/cli/archive/mod.rs
  src/bin/cli/mod.rs
  src/lib.rs
Labels: refactor

#49 Vote check tool
  Cargo.lock
  Cargo.toml
  README.md
  resources/explorer/schema.graphql
  resources/explorer/transaction_by_id.graphql
  src/bin/cli/mod.rs
  src/bin/cli/vote_check/mod.rs
  src/lib.rs
  src/vote_check/explorer.rs
  src/vote_check/mod.rs
Labels: enhancement
