Repository input-output-hk/catalyst-toolbox, pull requests merged in 2022-02, with the labels that each got.

#94 Update dependencies
  Cargo.lock
  Cargo.toml
  src/bin/cli/rewards/voters.rs
  src/recovery/tally.rs
  src/rewards/voters.rs
  src/vote_check/mod.rs
  tests/tally/blockchain.rs
  tests/tally/generator.rs
  tests/tally/main.rs
Labels: testing

#83 Ideascale importer mk explanation
  doc/ideascale_importer.md
Labels: documentation

#100 add coverage report to CI
  .github/workflows/test.yml
Labels: testing

#102 add integration with coverall
  .github/workflows/test.yml
Labels: CI

#101 wrap python script into rust struct and expose testing module
  Cargo.lock
  Cargo.toml
  scripts/python/proposers_rewards.py
  src/bin/cli/advisor_reviews/mod.rs
  src/lib.rs
  src/testing.rs
Labels: testing
